// Warning: Don't edit file (autogenerated from python -m dev codegen).

export const ROBOCODE_GET_LANGUAGE_SERVER_PYTHON = "robocode.getLanguageServerPython";  // Get a python executable suitable to start the language server.
export const ROBOCODE_CREATE_ACTIVITY = "robocode.createActivity";  // Create a Robocode Activity Package.
export const ROBOCODE_LIST_ACTIVITY_TEMPLATES_INTERNAL = "robocode.listActivityTemplates.internal";  // Provides a list with the available activity templates.
export const ROBOCODE_CREATE_ACTIVITY_INTERNAL = "robocode.createActivity.internal";  // Actually calls rcc to create the activity.