// Warning: Don't edit file (autogenerated from python -m dev codegen).

export const ROBOCODE_GET_LANGUAGE_SERVER_PYTHON = "robocode.getLanguageServerPython";  // Get a python executable suitable to start the language server.
export const ROBOCODE_SAY_HELLO = "robocode.sayHello";  // Hello World