#!/usr/bin/env bash
set -eux

pushd src
python -m pip install -e .
popd

jupyter labextension install --no-build \
  jupyterlab_robotmode@1.1.1 \
  @krassowski/jupyterlab-lsp@0.7.1

jupyter lab build --dev-build=False --minimize=True
