package robocorp.robot.intellij;

import com.google.gson.*;
import com.intellij.openapi.components.PersistentStateComponent;
import com.intellij.openapi.components.ServiceManager;
import com.intellij.openapi.components.State;
import com.intellij.openapi.components.Storage;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.progress.ProcessCanceledException;
import com.intellij.openapi.project.Project;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import robocorp.lsp.intellij.LanguageServerDefinition;

import java.util.Collection;
import java.util.concurrent.CopyOnWriteArraySet;


class RobotProjectState {
    
    public String robotLanguageServerPython = "";
    public String robotLanguageServerArgs = "";
    public String robotLanguageServerTcpPort = "";
    public String robotPythonExecutable = "";
    public String robotPythonEnv = "";
    public String robotVariables = "";
    public String robotLoadVariablesFromArgumentsFile = "";
    public String robotPythonpath = "";
    public String robotLibrariesLibdocNeedsArgs = "";
    public String robotLibrariesLibdocPreGenerate = "";
    public String robotCodeFormatter = "";
    public String robotFlowExplorerTheme = "";
    public String robotLintRobocopEnabled = "";
    public String robotLintEnabled = "";
    public String robotLintUndefinedKeywords = "";
    public String robotLintUndefinedLibraries = "";
    public String robotLintUndefinedResources = "";
    public String robotLintUndefinedVariableImports = "";
    public String robotLintKeywordCallArguments = "";
    public String robotLintKeywordResolvesToMultipleKeywords = "";
    public String robotLintVariables = "";
    public String robotLintIgnoreVariables = "";
    public String robotLintIgnoreEnvironmentVariables = "";
    public String robotLintUnusedKeyword = "";
    public String robotCompletionsSectionHeadersForm = "";
    public String robotCompletionsKeywordsFormat = "";
    public String robotCompletionsKeywordsArgumentsSeparator = "";
    public String robotWorkspaceSymbolsOnlyForOpenDocs = "";
}

// IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
@State(name = "RobotProjectPreferences", storages = {@Storage("RobotProjectPreferences.xml")})
public class RobotProjectPreferences implements PersistentStateComponent<RobotState> {

    
    public static final String ROBOT_LANGUAGE_SERVER_PYTHON = "robot.language-server.python";
    public static final String ROBOT_LANGUAGE_SERVER_ARGS = "robot.language-server.args";
    public static final String ROBOT_LANGUAGE_SERVER_TCP_PORT = "robot.language-server.tcp-port";
    public static final String ROBOT_PYTHON_EXECUTABLE = "robot.python.executable";
    public static final String ROBOT_PYTHON_ENV = "robot.python.env";
    public static final String ROBOT_VARIABLES = "robot.variables";
    public static final String ROBOT_LOAD_VARIABLES_FROM_ARGUMENTS_FILE = "robot.loadVariablesFromArgumentsFile";
    public static final String ROBOT_PYTHONPATH = "robot.pythonpath";
    public static final String ROBOT_LIBRARIES_LIBDOC_NEEDS_ARGS = "robot.libraries.libdoc.needsArgs";
    public static final String ROBOT_LIBRARIES_LIBDOC_PRE_GENERATE = "robot.libraries.libdoc.preGenerate";
    public static final String ROBOT_CODE_FORMATTER = "robot.codeFormatter";
    public static final String ROBOT_FLOW_EXPLORER_THEME = "robot.flowExplorerTheme";
    public static final String ROBOT_LINT_ROBOCOP_ENABLED = "robot.lint.robocop.enabled";
    public static final String ROBOT_LINT_ENABLED = "robot.lint.enabled";
    public static final String ROBOT_LINT_UNDEFINED_KEYWORDS = "robot.lint.undefinedKeywords";
    public static final String ROBOT_LINT_UNDEFINED_LIBRARIES = "robot.lint.undefinedLibraries";
    public static final String ROBOT_LINT_UNDEFINED_RESOURCES = "robot.lint.undefinedResources";
    public static final String ROBOT_LINT_UNDEFINED_VARIABLE_IMPORTS = "robot.lint.undefinedVariableImports";
    public static final String ROBOT_LINT_KEYWORD_CALL_ARGUMENTS = "robot.lint.keywordCallArguments";
    public static final String ROBOT_LINT_KEYWORD_RESOLVES_TO_MULTIPLE_KEYWORDS = "robot.lint.keywordResolvesToMultipleKeywords";
    public static final String ROBOT_LINT_VARIABLES = "robot.lint.variables";
    public static final String ROBOT_LINT_IGNORE_VARIABLES = "robot.lint.ignoreVariables";
    public static final String ROBOT_LINT_IGNORE_ENVIRONMENT_VARIABLES = "robot.lint.ignoreEnvironmentVariables";
    public static final String ROBOT_LINT_UNUSED_KEYWORD = "robot.lint.unusedKeyword";
    public static final String ROBOT_COMPLETIONS_SECTION_HEADERS_FORM = "robot.completions.section_headers.form";
    public static final String ROBOT_COMPLETIONS_KEYWORDS_FORMAT = "robot.completions.keywords.format";
    public static final String ROBOT_COMPLETIONS_KEYWORDS_ARGUMENTS_SEPARATOR = "robot.completions.keywords.argumentsSeparator";
    public static final String ROBOT_WORKSPACE_SYMBOLS_ONLY_FOR_OPEN_DOCS = "robot.workspaceSymbolsOnlyForOpenDocs";

    private static final Logger LOG = Logger.getInstance(RobotProjectPreferences.class);

    // IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
    @Nullable
    @Override
    public RobotState getState() {
        RobotState robotState = new RobotState();
        
        robotState.robotLanguageServerPython = getRobotLanguageServerPython();
        robotState.robotLanguageServerArgs = getRobotLanguageServerArgs();
        robotState.robotLanguageServerTcpPort = getRobotLanguageServerTcpPort();
        robotState.robotPythonExecutable = getRobotPythonExecutable();
        robotState.robotPythonEnv = getRobotPythonEnv();
        robotState.robotVariables = getRobotVariables();
        robotState.robotLoadVariablesFromArgumentsFile = getRobotLoadVariablesFromArgumentsFile();
        robotState.robotPythonpath = getRobotPythonpath();
        robotState.robotLibrariesLibdocNeedsArgs = getRobotLibrariesLibdocNeedsArgs();
        robotState.robotLibrariesLibdocPreGenerate = getRobotLibrariesLibdocPreGenerate();
        robotState.robotCodeFormatter = getRobotCodeFormatter();
        robotState.robotFlowExplorerTheme = getRobotFlowExplorerTheme();
        robotState.robotLintRobocopEnabled = getRobotLintRobocopEnabled();
        robotState.robotLintEnabled = getRobotLintEnabled();
        robotState.robotLintUndefinedKeywords = getRobotLintUndefinedKeywords();
        robotState.robotLintUndefinedLibraries = getRobotLintUndefinedLibraries();
        robotState.robotLintUndefinedResources = getRobotLintUndefinedResources();
        robotState.robotLintUndefinedVariableImports = getRobotLintUndefinedVariableImports();
        robotState.robotLintKeywordCallArguments = getRobotLintKeywordCallArguments();
        robotState.robotLintKeywordResolvesToMultipleKeywords = getRobotLintKeywordResolvesToMultipleKeywords();
        robotState.robotLintVariables = getRobotLintVariables();
        robotState.robotLintIgnoreVariables = getRobotLintIgnoreVariables();
        robotState.robotLintIgnoreEnvironmentVariables = getRobotLintIgnoreEnvironmentVariables();
        robotState.robotLintUnusedKeyword = getRobotLintUnusedKeyword();
        robotState.robotCompletionsSectionHeadersForm = getRobotCompletionsSectionHeadersForm();
        robotState.robotCompletionsKeywordsFormat = getRobotCompletionsKeywordsFormat();
        robotState.robotCompletionsKeywordsArgumentsSeparator = getRobotCompletionsKeywordsArgumentsSeparator();
        robotState.robotWorkspaceSymbolsOnlyForOpenDocs = getRobotWorkspaceSymbolsOnlyForOpenDocs();
        return robotState;
    }

    // IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
    @Override
    public void loadState(@NotNull RobotState robotState) {
        
        setRobotLanguageServerPython(robotState.robotLanguageServerPython);
        setRobotLanguageServerArgs(robotState.robotLanguageServerArgs);
        setRobotLanguageServerTcpPort(robotState.robotLanguageServerTcpPort);
        setRobotPythonExecutable(robotState.robotPythonExecutable);
        setRobotPythonEnv(robotState.robotPythonEnv);
        setRobotVariables(robotState.robotVariables);
        setRobotLoadVariablesFromArgumentsFile(robotState.robotLoadVariablesFromArgumentsFile);
        setRobotPythonpath(robotState.robotPythonpath);
        setRobotLibrariesLibdocNeedsArgs(robotState.robotLibrariesLibdocNeedsArgs);
        setRobotLibrariesLibdocPreGenerate(robotState.robotLibrariesLibdocPreGenerate);
        setRobotCodeFormatter(robotState.robotCodeFormatter);
        setRobotFlowExplorerTheme(robotState.robotFlowExplorerTheme);
        setRobotLintRobocopEnabled(robotState.robotLintRobocopEnabled);
        setRobotLintEnabled(robotState.robotLintEnabled);
        setRobotLintUndefinedKeywords(robotState.robotLintUndefinedKeywords);
        setRobotLintUndefinedLibraries(robotState.robotLintUndefinedLibraries);
        setRobotLintUndefinedResources(robotState.robotLintUndefinedResources);
        setRobotLintUndefinedVariableImports(robotState.robotLintUndefinedVariableImports);
        setRobotLintKeywordCallArguments(robotState.robotLintKeywordCallArguments);
        setRobotLintKeywordResolvesToMultipleKeywords(robotState.robotLintKeywordResolvesToMultipleKeywords);
        setRobotLintVariables(robotState.robotLintVariables);
        setRobotLintIgnoreVariables(robotState.robotLintIgnoreVariables);
        setRobotLintIgnoreEnvironmentVariables(robotState.robotLintIgnoreEnvironmentVariables);
        setRobotLintUnusedKeyword(robotState.robotLintUnusedKeyword);
        setRobotCompletionsSectionHeadersForm(robotState.robotCompletionsSectionHeadersForm);
        setRobotCompletionsKeywordsFormat(robotState.robotCompletionsKeywordsFormat);
        setRobotCompletionsKeywordsArgumentsSeparator(robotState.robotCompletionsKeywordsArgumentsSeparator);
        setRobotWorkspaceSymbolsOnlyForOpenDocs(robotState.robotWorkspaceSymbolsOnlyForOpenDocs);
    }

    // IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
    public JsonObject asJsonObject() {
        JsonObject jsonObject = new JsonObject();
        
        if(!robotLanguageServerPython.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LANGUAGE_SERVER_PYTHON, new JsonPrimitive(robotLanguageServerPython));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLanguageServerArgs.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_LANGUAGE_SERVER_ARGS, g.fromJson(robotLanguageServerArgs, JsonArray.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLanguageServerTcpPort.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LANGUAGE_SERVER_TCP_PORT, new JsonPrimitive(Integer.parseInt(robotLanguageServerTcpPort)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotPythonExecutable.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_PYTHON_EXECUTABLE, new JsonPrimitive(robotPythonExecutable));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotPythonEnv.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_PYTHON_ENV, g.fromJson(robotPythonEnv, JsonObject.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotVariables.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_VARIABLES, g.fromJson(robotVariables, JsonObject.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLoadVariablesFromArgumentsFile.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LOAD_VARIABLES_FROM_ARGUMENTS_FILE, new JsonPrimitive(robotLoadVariablesFromArgumentsFile));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotPythonpath.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_PYTHONPATH, g.fromJson(robotPythonpath, JsonArray.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLibrariesLibdocNeedsArgs.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_LIBRARIES_LIBDOC_NEEDS_ARGS, g.fromJson(robotLibrariesLibdocNeedsArgs, JsonArray.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLibrariesLibdocPreGenerate.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_LIBRARIES_LIBDOC_PRE_GENERATE, g.fromJson(robotLibrariesLibdocPreGenerate, JsonArray.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotCodeFormatter.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_CODE_FORMATTER, new JsonPrimitive(robotCodeFormatter));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotFlowExplorerTheme.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_FLOW_EXPLORER_THEME, new JsonPrimitive(robotFlowExplorerTheme));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintRobocopEnabled.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_ROBOCOP_ENABLED, new JsonPrimitive(Boolean.parseBoolean(robotLintRobocopEnabled)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintEnabled.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_ENABLED, new JsonPrimitive(Boolean.parseBoolean(robotLintEnabled)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintUndefinedKeywords.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_UNDEFINED_KEYWORDS, new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedKeywords)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintUndefinedLibraries.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_UNDEFINED_LIBRARIES, new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedLibraries)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintUndefinedResources.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_UNDEFINED_RESOURCES, new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedResources)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintUndefinedVariableImports.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_UNDEFINED_VARIABLE_IMPORTS, new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedVariableImports)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintKeywordCallArguments.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_KEYWORD_CALL_ARGUMENTS, new JsonPrimitive(Boolean.parseBoolean(robotLintKeywordCallArguments)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintKeywordResolvesToMultipleKeywords.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_KEYWORD_RESOLVES_TO_MULTIPLE_KEYWORDS, new JsonPrimitive(Boolean.parseBoolean(robotLintKeywordResolvesToMultipleKeywords)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintVariables.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_VARIABLES, new JsonPrimitive(Boolean.parseBoolean(robotLintVariables)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintIgnoreVariables.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_LINT_IGNORE_VARIABLES, g.fromJson(robotLintIgnoreVariables, JsonArray.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintIgnoreEnvironmentVariables.isEmpty()){
            Gson g = new Gson();
            try {
                jsonObject.add(ROBOT_LINT_IGNORE_ENVIRONMENT_VARIABLES, g.fromJson(robotLintIgnoreEnvironmentVariables, JsonArray.class));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotLintUnusedKeyword.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_LINT_UNUSED_KEYWORD, new JsonPrimitive(Boolean.parseBoolean(robotLintUnusedKeyword)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotCompletionsSectionHeadersForm.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_COMPLETIONS_SECTION_HEADERS_FORM, new JsonPrimitive(robotCompletionsSectionHeadersForm));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotCompletionsKeywordsFormat.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_COMPLETIONS_KEYWORDS_FORMAT, new JsonPrimitive(robotCompletionsKeywordsFormat));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotCompletionsKeywordsArgumentsSeparator.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_COMPLETIONS_KEYWORDS_ARGUMENTS_SEPARATOR, new JsonPrimitive(robotCompletionsKeywordsArgumentsSeparator));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        if(!robotWorkspaceSymbolsOnlyForOpenDocs.isEmpty()){
            
            try {
                jsonObject.add(ROBOT_WORKSPACE_SYMBOLS_ONLY_FOR_OPEN_DOCS, new JsonPrimitive(Boolean.parseBoolean(robotWorkspaceSymbolsOnlyForOpenDocs)));
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        
        return jsonObject;
    }

    
    private String robotLanguageServerPython = "";

    public @NotNull String getRobotLanguageServerPython() {
        return robotLanguageServerPython;
    }

    public @Nullable JsonPrimitive getRobotLanguageServerPythonAsJson() {
        if(robotLanguageServerPython.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotLanguageServerPython);
    }

    public @NotNull String validateRobotLanguageServerPython(String robotLanguageServerPython) {
        if(robotLanguageServerPython.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotLanguageServerPython);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLanguageServerPython(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLanguageServerPython)) {
            return;
        }
        String old = robotLanguageServerPython;
        robotLanguageServerPython = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LANGUAGE_SERVER_PYTHON, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLanguageServerArgs = "";

    public @NotNull String getRobotLanguageServerArgs() {
        return robotLanguageServerArgs;
    }

    public @Nullable JsonArray getRobotLanguageServerArgsAsJson() {
        if(robotLanguageServerArgs.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotLanguageServerArgs, JsonArray.class);
    }

    public @NotNull String validateRobotLanguageServerArgs(String robotLanguageServerArgs) {
        if(robotLanguageServerArgs.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotLanguageServerArgs, JsonArray.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLanguageServerArgs(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLanguageServerArgs)) {
            return;
        }
        String old = robotLanguageServerArgs;
        robotLanguageServerArgs = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LANGUAGE_SERVER_ARGS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLanguageServerTcpPort = "";

    public @NotNull String getRobotLanguageServerTcpPort() {
        return robotLanguageServerTcpPort;
    }

    public @Nullable JsonPrimitive getRobotLanguageServerTcpPortAsJson() {
        if(robotLanguageServerTcpPort.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Integer.parseInt(robotLanguageServerTcpPort));
    }

    public @NotNull String validateRobotLanguageServerTcpPort(String robotLanguageServerTcpPort) {
        if(robotLanguageServerTcpPort.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Integer.parseInt(robotLanguageServerTcpPort));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLanguageServerTcpPort(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLanguageServerTcpPort)) {
            return;
        }
        String old = robotLanguageServerTcpPort;
        robotLanguageServerTcpPort = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LANGUAGE_SERVER_TCP_PORT, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotPythonExecutable = "";

    public @NotNull String getRobotPythonExecutable() {
        return robotPythonExecutable;
    }

    public @Nullable JsonPrimitive getRobotPythonExecutableAsJson() {
        if(robotPythonExecutable.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotPythonExecutable);
    }

    public @NotNull String validateRobotPythonExecutable(String robotPythonExecutable) {
        if(robotPythonExecutable.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotPythonExecutable);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotPythonExecutable(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotPythonExecutable)) {
            return;
        }
        String old = robotPythonExecutable;
        robotPythonExecutable = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_PYTHON_EXECUTABLE, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotPythonEnv = "";

    public @NotNull String getRobotPythonEnv() {
        return robotPythonEnv;
    }

    public @Nullable JsonObject getRobotPythonEnvAsJson() {
        if(robotPythonEnv.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotPythonEnv, JsonObject.class);
    }

    public @NotNull String validateRobotPythonEnv(String robotPythonEnv) {
        if(robotPythonEnv.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotPythonEnv, JsonObject.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotPythonEnv(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotPythonEnv)) {
            return;
        }
        String old = robotPythonEnv;
        robotPythonEnv = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_PYTHON_ENV, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotVariables = "";

    public @NotNull String getRobotVariables() {
        return robotVariables;
    }

    public @Nullable JsonObject getRobotVariablesAsJson() {
        if(robotVariables.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotVariables, JsonObject.class);
    }

    public @NotNull String validateRobotVariables(String robotVariables) {
        if(robotVariables.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotVariables, JsonObject.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotVariables(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotVariables)) {
            return;
        }
        String old = robotVariables;
        robotVariables = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_VARIABLES, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLoadVariablesFromArgumentsFile = "";

    public @NotNull String getRobotLoadVariablesFromArgumentsFile() {
        return robotLoadVariablesFromArgumentsFile;
    }

    public @Nullable JsonPrimitive getRobotLoadVariablesFromArgumentsFileAsJson() {
        if(robotLoadVariablesFromArgumentsFile.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotLoadVariablesFromArgumentsFile);
    }

    public @NotNull String validateRobotLoadVariablesFromArgumentsFile(String robotLoadVariablesFromArgumentsFile) {
        if(robotLoadVariablesFromArgumentsFile.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotLoadVariablesFromArgumentsFile);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLoadVariablesFromArgumentsFile(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLoadVariablesFromArgumentsFile)) {
            return;
        }
        String old = robotLoadVariablesFromArgumentsFile;
        robotLoadVariablesFromArgumentsFile = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LOAD_VARIABLES_FROM_ARGUMENTS_FILE, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotPythonpath = "";

    public @NotNull String getRobotPythonpath() {
        return robotPythonpath;
    }

    public @Nullable JsonArray getRobotPythonpathAsJson() {
        if(robotPythonpath.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotPythonpath, JsonArray.class);
    }

    public @NotNull String validateRobotPythonpath(String robotPythonpath) {
        if(robotPythonpath.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotPythonpath, JsonArray.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotPythonpath(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotPythonpath)) {
            return;
        }
        String old = robotPythonpath;
        robotPythonpath = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_PYTHONPATH, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLibrariesLibdocNeedsArgs = "";

    public @NotNull String getRobotLibrariesLibdocNeedsArgs() {
        return robotLibrariesLibdocNeedsArgs;
    }

    public @Nullable JsonArray getRobotLibrariesLibdocNeedsArgsAsJson() {
        if(robotLibrariesLibdocNeedsArgs.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotLibrariesLibdocNeedsArgs, JsonArray.class);
    }

    public @NotNull String validateRobotLibrariesLibdocNeedsArgs(String robotLibrariesLibdocNeedsArgs) {
        if(robotLibrariesLibdocNeedsArgs.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotLibrariesLibdocNeedsArgs, JsonArray.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLibrariesLibdocNeedsArgs(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLibrariesLibdocNeedsArgs)) {
            return;
        }
        String old = robotLibrariesLibdocNeedsArgs;
        robotLibrariesLibdocNeedsArgs = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LIBRARIES_LIBDOC_NEEDS_ARGS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLibrariesLibdocPreGenerate = "";

    public @NotNull String getRobotLibrariesLibdocPreGenerate() {
        return robotLibrariesLibdocPreGenerate;
    }

    public @Nullable JsonArray getRobotLibrariesLibdocPreGenerateAsJson() {
        if(robotLibrariesLibdocPreGenerate.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotLibrariesLibdocPreGenerate, JsonArray.class);
    }

    public @NotNull String validateRobotLibrariesLibdocPreGenerate(String robotLibrariesLibdocPreGenerate) {
        if(robotLibrariesLibdocPreGenerate.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotLibrariesLibdocPreGenerate, JsonArray.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLibrariesLibdocPreGenerate(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLibrariesLibdocPreGenerate)) {
            return;
        }
        String old = robotLibrariesLibdocPreGenerate;
        robotLibrariesLibdocPreGenerate = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LIBRARIES_LIBDOC_PRE_GENERATE, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotCodeFormatter = "";

    public @NotNull String getRobotCodeFormatter() {
        return robotCodeFormatter;
    }

    public @Nullable JsonPrimitive getRobotCodeFormatterAsJson() {
        if(robotCodeFormatter.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotCodeFormatter);
    }

    public @NotNull String validateRobotCodeFormatter(String robotCodeFormatter) {
        if(robotCodeFormatter.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotCodeFormatter);
             
            if(robotCodeFormatter.equalsIgnoreCase("robotidy")){
                return "";
            }
            if(robotCodeFormatter.equalsIgnoreCase("builtinTidy")){
                return "";
            }
            return "Unexpected value: " + robotCodeFormatter;
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotCodeFormatter(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotCodeFormatter)) {
            return;
        }
        String old = robotCodeFormatter;
        robotCodeFormatter = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_CODE_FORMATTER, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotFlowExplorerTheme = "";

    public @NotNull String getRobotFlowExplorerTheme() {
        return robotFlowExplorerTheme;
    }

    public @Nullable JsonPrimitive getRobotFlowExplorerThemeAsJson() {
        if(robotFlowExplorerTheme.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotFlowExplorerTheme);
    }

    public @NotNull String validateRobotFlowExplorerTheme(String robotFlowExplorerTheme) {
        if(robotFlowExplorerTheme.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotFlowExplorerTheme);
             
            if(robotFlowExplorerTheme.equalsIgnoreCase("dark")){
                return "";
            }
            if(robotFlowExplorerTheme.equalsIgnoreCase("light")){
                return "";
            }
            return "Unexpected value: " + robotFlowExplorerTheme;
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotFlowExplorerTheme(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotFlowExplorerTheme)) {
            return;
        }
        String old = robotFlowExplorerTheme;
        robotFlowExplorerTheme = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_FLOW_EXPLORER_THEME, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintRobocopEnabled = "";

    public @NotNull String getRobotLintRobocopEnabled() {
        return robotLintRobocopEnabled;
    }

    public @Nullable JsonPrimitive getRobotLintRobocopEnabledAsJson() {
        if(robotLintRobocopEnabled.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintRobocopEnabled));
    }

    public @NotNull String validateRobotLintRobocopEnabled(String robotLintRobocopEnabled) {
        if(robotLintRobocopEnabled.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintRobocopEnabled));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintRobocopEnabled(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintRobocopEnabled)) {
            return;
        }
        String old = robotLintRobocopEnabled;
        robotLintRobocopEnabled = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_ROBOCOP_ENABLED, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintEnabled = "";

    public @NotNull String getRobotLintEnabled() {
        return robotLintEnabled;
    }

    public @Nullable JsonPrimitive getRobotLintEnabledAsJson() {
        if(robotLintEnabled.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintEnabled));
    }

    public @NotNull String validateRobotLintEnabled(String robotLintEnabled) {
        if(robotLintEnabled.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintEnabled));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintEnabled(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintEnabled)) {
            return;
        }
        String old = robotLintEnabled;
        robotLintEnabled = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_ENABLED, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintUndefinedKeywords = "";

    public @NotNull String getRobotLintUndefinedKeywords() {
        return robotLintUndefinedKeywords;
    }

    public @Nullable JsonPrimitive getRobotLintUndefinedKeywordsAsJson() {
        if(robotLintUndefinedKeywords.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedKeywords));
    }

    public @NotNull String validateRobotLintUndefinedKeywords(String robotLintUndefinedKeywords) {
        if(robotLintUndefinedKeywords.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedKeywords));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintUndefinedKeywords(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintUndefinedKeywords)) {
            return;
        }
        String old = robotLintUndefinedKeywords;
        robotLintUndefinedKeywords = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_UNDEFINED_KEYWORDS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintUndefinedLibraries = "";

    public @NotNull String getRobotLintUndefinedLibraries() {
        return robotLintUndefinedLibraries;
    }

    public @Nullable JsonPrimitive getRobotLintUndefinedLibrariesAsJson() {
        if(robotLintUndefinedLibraries.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedLibraries));
    }

    public @NotNull String validateRobotLintUndefinedLibraries(String robotLintUndefinedLibraries) {
        if(robotLintUndefinedLibraries.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedLibraries));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintUndefinedLibraries(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintUndefinedLibraries)) {
            return;
        }
        String old = robotLintUndefinedLibraries;
        robotLintUndefinedLibraries = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_UNDEFINED_LIBRARIES, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintUndefinedResources = "";

    public @NotNull String getRobotLintUndefinedResources() {
        return robotLintUndefinedResources;
    }

    public @Nullable JsonPrimitive getRobotLintUndefinedResourcesAsJson() {
        if(robotLintUndefinedResources.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedResources));
    }

    public @NotNull String validateRobotLintUndefinedResources(String robotLintUndefinedResources) {
        if(robotLintUndefinedResources.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedResources));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintUndefinedResources(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintUndefinedResources)) {
            return;
        }
        String old = robotLintUndefinedResources;
        robotLintUndefinedResources = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_UNDEFINED_RESOURCES, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintUndefinedVariableImports = "";

    public @NotNull String getRobotLintUndefinedVariableImports() {
        return robotLintUndefinedVariableImports;
    }

    public @Nullable JsonPrimitive getRobotLintUndefinedVariableImportsAsJson() {
        if(robotLintUndefinedVariableImports.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedVariableImports));
    }

    public @NotNull String validateRobotLintUndefinedVariableImports(String robotLintUndefinedVariableImports) {
        if(robotLintUndefinedVariableImports.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintUndefinedVariableImports));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintUndefinedVariableImports(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintUndefinedVariableImports)) {
            return;
        }
        String old = robotLintUndefinedVariableImports;
        robotLintUndefinedVariableImports = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_UNDEFINED_VARIABLE_IMPORTS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintKeywordCallArguments = "";

    public @NotNull String getRobotLintKeywordCallArguments() {
        return robotLintKeywordCallArguments;
    }

    public @Nullable JsonPrimitive getRobotLintKeywordCallArgumentsAsJson() {
        if(robotLintKeywordCallArguments.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintKeywordCallArguments));
    }

    public @NotNull String validateRobotLintKeywordCallArguments(String robotLintKeywordCallArguments) {
        if(robotLintKeywordCallArguments.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintKeywordCallArguments));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintKeywordCallArguments(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintKeywordCallArguments)) {
            return;
        }
        String old = robotLintKeywordCallArguments;
        robotLintKeywordCallArguments = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_KEYWORD_CALL_ARGUMENTS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintKeywordResolvesToMultipleKeywords = "";

    public @NotNull String getRobotLintKeywordResolvesToMultipleKeywords() {
        return robotLintKeywordResolvesToMultipleKeywords;
    }

    public @Nullable JsonPrimitive getRobotLintKeywordResolvesToMultipleKeywordsAsJson() {
        if(robotLintKeywordResolvesToMultipleKeywords.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintKeywordResolvesToMultipleKeywords));
    }

    public @NotNull String validateRobotLintKeywordResolvesToMultipleKeywords(String robotLintKeywordResolvesToMultipleKeywords) {
        if(robotLintKeywordResolvesToMultipleKeywords.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintKeywordResolvesToMultipleKeywords));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintKeywordResolvesToMultipleKeywords(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintKeywordResolvesToMultipleKeywords)) {
            return;
        }
        String old = robotLintKeywordResolvesToMultipleKeywords;
        robotLintKeywordResolvesToMultipleKeywords = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_KEYWORD_RESOLVES_TO_MULTIPLE_KEYWORDS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintVariables = "";

    public @NotNull String getRobotLintVariables() {
        return robotLintVariables;
    }

    public @Nullable JsonPrimitive getRobotLintVariablesAsJson() {
        if(robotLintVariables.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintVariables));
    }

    public @NotNull String validateRobotLintVariables(String robotLintVariables) {
        if(robotLintVariables.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintVariables));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintVariables(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintVariables)) {
            return;
        }
        String old = robotLintVariables;
        robotLintVariables = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_VARIABLES, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintIgnoreVariables = "";

    public @NotNull String getRobotLintIgnoreVariables() {
        return robotLintIgnoreVariables;
    }

    public @Nullable JsonArray getRobotLintIgnoreVariablesAsJson() {
        if(robotLintIgnoreVariables.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotLintIgnoreVariables, JsonArray.class);
    }

    public @NotNull String validateRobotLintIgnoreVariables(String robotLintIgnoreVariables) {
        if(robotLintIgnoreVariables.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotLintIgnoreVariables, JsonArray.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintIgnoreVariables(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintIgnoreVariables)) {
            return;
        }
        String old = robotLintIgnoreVariables;
        robotLintIgnoreVariables = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_IGNORE_VARIABLES, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintIgnoreEnvironmentVariables = "";

    public @NotNull String getRobotLintIgnoreEnvironmentVariables() {
        return robotLintIgnoreEnvironmentVariables;
    }

    public @Nullable JsonArray getRobotLintIgnoreEnvironmentVariablesAsJson() {
        if(robotLintIgnoreEnvironmentVariables.isEmpty()){
            return null;
        }
        Gson g = new Gson();
        return g.fromJson(robotLintIgnoreEnvironmentVariables, JsonArray.class);
    }

    public @NotNull String validateRobotLintIgnoreEnvironmentVariables(String robotLintIgnoreEnvironmentVariables) {
        if(robotLintIgnoreEnvironmentVariables.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            g.fromJson(robotLintIgnoreEnvironmentVariables, JsonArray.class);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintIgnoreEnvironmentVariables(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintIgnoreEnvironmentVariables)) {
            return;
        }
        String old = robotLintIgnoreEnvironmentVariables;
        robotLintIgnoreEnvironmentVariables = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_IGNORE_ENVIRONMENT_VARIABLES, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotLintUnusedKeyword = "";

    public @NotNull String getRobotLintUnusedKeyword() {
        return robotLintUnusedKeyword;
    }

    public @Nullable JsonPrimitive getRobotLintUnusedKeywordAsJson() {
        if(robotLintUnusedKeyword.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotLintUnusedKeyword));
    }

    public @NotNull String validateRobotLintUnusedKeyword(String robotLintUnusedKeyword) {
        if(robotLintUnusedKeyword.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotLintUnusedKeyword));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotLintUnusedKeyword(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotLintUnusedKeyword)) {
            return;
        }
        String old = robotLintUnusedKeyword;
        robotLintUnusedKeyword = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_LINT_UNUSED_KEYWORD, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotCompletionsSectionHeadersForm = "";

    public @NotNull String getRobotCompletionsSectionHeadersForm() {
        return robotCompletionsSectionHeadersForm;
    }

    public @Nullable JsonPrimitive getRobotCompletionsSectionHeadersFormAsJson() {
        if(robotCompletionsSectionHeadersForm.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotCompletionsSectionHeadersForm);
    }

    public @NotNull String validateRobotCompletionsSectionHeadersForm(String robotCompletionsSectionHeadersForm) {
        if(robotCompletionsSectionHeadersForm.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotCompletionsSectionHeadersForm);
             
            if(robotCompletionsSectionHeadersForm.equalsIgnoreCase("plural")){
                return "";
            }
            if(robotCompletionsSectionHeadersForm.equalsIgnoreCase("singular")){
                return "";
            }
            if(robotCompletionsSectionHeadersForm.equalsIgnoreCase("both")){
                return "";
            }
            return "Unexpected value: " + robotCompletionsSectionHeadersForm;
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotCompletionsSectionHeadersForm(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotCompletionsSectionHeadersForm)) {
            return;
        }
        String old = robotCompletionsSectionHeadersForm;
        robotCompletionsSectionHeadersForm = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_COMPLETIONS_SECTION_HEADERS_FORM, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotCompletionsKeywordsFormat = "";

    public @NotNull String getRobotCompletionsKeywordsFormat() {
        return robotCompletionsKeywordsFormat;
    }

    public @Nullable JsonPrimitive getRobotCompletionsKeywordsFormatAsJson() {
        if(robotCompletionsKeywordsFormat.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotCompletionsKeywordsFormat);
    }

    public @NotNull String validateRobotCompletionsKeywordsFormat(String robotCompletionsKeywordsFormat) {
        if(robotCompletionsKeywordsFormat.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotCompletionsKeywordsFormat);
             
            if(robotCompletionsKeywordsFormat.equalsIgnoreCase("First upper")){
                return "";
            }
            if(robotCompletionsKeywordsFormat.equalsIgnoreCase("Title Case")){
                return "";
            }
            if(robotCompletionsKeywordsFormat.equalsIgnoreCase("ALL UPPER")){
                return "";
            }
            if(robotCompletionsKeywordsFormat.equalsIgnoreCase("all lower")){
                return "";
            }
            return "Unexpected value: " + robotCompletionsKeywordsFormat;
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotCompletionsKeywordsFormat(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotCompletionsKeywordsFormat)) {
            return;
        }
        String old = robotCompletionsKeywordsFormat;
        robotCompletionsKeywordsFormat = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_COMPLETIONS_KEYWORDS_FORMAT, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotCompletionsKeywordsArgumentsSeparator = "";

    public @NotNull String getRobotCompletionsKeywordsArgumentsSeparator() {
        return robotCompletionsKeywordsArgumentsSeparator;
    }

    public @Nullable JsonPrimitive getRobotCompletionsKeywordsArgumentsSeparatorAsJson() {
        if(robotCompletionsKeywordsArgumentsSeparator.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(robotCompletionsKeywordsArgumentsSeparator);
    }

    public @NotNull String validateRobotCompletionsKeywordsArgumentsSeparator(String robotCompletionsKeywordsArgumentsSeparator) {
        if(robotCompletionsKeywordsArgumentsSeparator.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(robotCompletionsKeywordsArgumentsSeparator);
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotCompletionsKeywordsArgumentsSeparator(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotCompletionsKeywordsArgumentsSeparator)) {
            return;
        }
        String old = robotCompletionsKeywordsArgumentsSeparator;
        robotCompletionsKeywordsArgumentsSeparator = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_COMPLETIONS_KEYWORDS_ARGUMENTS_SEPARATOR, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    
    private String robotWorkspaceSymbolsOnlyForOpenDocs = "";

    public @NotNull String getRobotWorkspaceSymbolsOnlyForOpenDocs() {
        return robotWorkspaceSymbolsOnlyForOpenDocs;
    }

    public @Nullable JsonPrimitive getRobotWorkspaceSymbolsOnlyForOpenDocsAsJson() {
        if(robotWorkspaceSymbolsOnlyForOpenDocs.isEmpty()){
            return null;
        }
        
        return new JsonPrimitive(Boolean.parseBoolean(robotWorkspaceSymbolsOnlyForOpenDocs));
    }

    public @NotNull String validateRobotWorkspaceSymbolsOnlyForOpenDocs(String robotWorkspaceSymbolsOnlyForOpenDocs) {
        if(robotWorkspaceSymbolsOnlyForOpenDocs.isEmpty()) {
            return "";
        }
        try {
            
            new JsonPrimitive(Boolean.parseBoolean(robotWorkspaceSymbolsOnlyForOpenDocs));
            
            return "";
            
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void setRobotWorkspaceSymbolsOnlyForOpenDocs(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals(robotWorkspaceSymbolsOnlyForOpenDocs)) {
            return;
        }
        String old = robotWorkspaceSymbolsOnlyForOpenDocs;
        robotWorkspaceSymbolsOnlyForOpenDocs = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            try {
                listener.onChanged(ROBOT_WORKSPACE_SYMBOLS_ONLY_FOR_OPEN_DOCS, old, s);
            } catch (CancelledException e) {
                // just ignore at this point
            }
        }
    }
    

    private Collection<LanguageServerDefinition.IPreferencesListener> listeners = new CopyOnWriteArraySet<>();

    public static @Nullable RobotProjectPreferences getInstance(Project project) throws CancelledException {
        try {
            return ServiceManager.getService(project, RobotProjectPreferences.class);
        } catch (ProcessCanceledException e) {
            throw new CancelledException(e);
        } catch (Exception e) {
            LOG.error("Error getting RobotProjectPreferences", e);
            return null;
        }
    }

    public void addListener(LanguageServerDefinition.IPreferencesListener listener) {
        listeners.add(listener);
    }

    public void removeListener(LanguageServerDefinition.IPreferencesListener listener) {
        listeners.remove(listener);
    }

}