// Warning: Don't edit file (autogenerated from python -m dev codegen).

export const TREE_VIEW_CONTAINER_ROBOCORP_ROBOTS = "robocorp-robots";  // Robocorp Code
export const TREE_VIEW_ROBOCORP_ROBOTS_TREE = "robocorp-robots-tree";  // Robocorp Code