#!/usr/bin/env bash
set -eux

# this runs _after_ `environment.yml` has been fulfilled, ensuring python, node,
# and jupyter tooling

# installs robotkernel with RF 3.2 support: add to `environment.yml` when released
pip install --no-deps --ignore-installed https://github.com/robots-from-jupyter/robotkernel/archive/d5a2980e76107103613b9390dcf8dbe271327d44.tar.gz

# installs the local development assets
pushd src
  python -m pip install -e . --ignore-installed --no-deps
popd

# install custom extensions with features for lsp and robotkernel
jupyter labextension install --no-build \
  @jupyter-widgets/jupyterlab-manager@1.1.0 \
  @krassowski/jupyterlab-lsp@0.7.1 \
  jupyterlab_robotmode@1.1.1

# build jupyterlab, optimized for hosting (5mb vs 35mb)
jupyter lab build --dev-build=False --minimize=True
