#!/usr/bin/env bash
set -eux

# this runs _after_ `environment.yml` has been fulfilled, ensuring python, node,
# and jupyter tooling

cd robotframework-ls

python -m dev vendor-robocorp-ls-core

cd src

python -m pip install -e . --ignore-installed --no-deps

jupyter kernelspec list
jupyter serverextension list
jupyter server extension list
jupyter labextension list
