import os
TEMPLATE_ROBOT_PREFERENCES_PAGE = '''package robocorp.robot.intellij;

import com.intellij.openapi.options.Configurable;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.util.NlsContexts;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBTextArea;
import com.intellij.ui.components.JBTextField;
import com.intellij.util.ui.FormBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import robocorp.lsp.intellij.LanguageServerDefinition;

import javax.swing.*;


// IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
class RobotPreferencesComponent {

    private final JPanel panel;
    {% for preference in preferences %}
    private final JBTextField {{ preference['java_name'] }} = new JBTextField();{% endfor %}

    public RobotPreferencesComponent() {
        panel = FormBuilder.createFormBuilder()
                {% for preference in preferences %}.addLabeledComponent(new JBLabel("{{ preference['visible_name'] }}"), {{ preference['java_name'] }}, 1, false)
                .addComponent(createJTextArea("{{ preference['description'] }}"))
                {% endfor %}
                .addComponentFillVertically(new JPanel(), 0)
                .getPanel();
    }

    private JBTextArea createJTextArea(String text) {
        JBTextArea f = new JBTextArea();
        f.setText(text);
        f.setEditable(false);
        f.setBackground(null);
        f.setBorder(null);
        f.setFont(UIManager.getFont("Label.font"));
        return f;
    }

    public JPanel getPanel() {
        return panel;
    }

    public JComponent getPreferredFocusedComponent() {
        return robotLanguageServerPython;
    }

    {% for preference in preferences %}
    @NotNull
    public String {{ preference['getter_name'] }}() {
        return {{ preference['java_name'] }}.getText();
    }

    public void {{ preference['setter_name'] }} (@NotNull String newText) {
        {{ preference['java_name'] }}.setText(newText);
    }
    {% endfor %}

}

// IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
public class RobotPreferencesPage implements Configurable {

    private RobotPreferencesComponent component;

    @Override
    public @NlsContexts.ConfigurableName String getDisplayName() {
        return "Robot Framework Language Server";
    }

    @Override
    public JComponent getPreferredFocusedComponent() {
        return component.getPreferredFocusedComponent();
    }

    @Override
    public @Nullable JComponent createComponent() {
        component = new RobotPreferencesComponent();
        return component.getPanel();
    }

    @Override
    public boolean isModified() {
        RobotPreferences settings = RobotPreferences.getInstance();
        {% for preference in preferences %}
        {% if (preference['type'] in ['string', 'array', 'object'] or True) %}if(!settings.{{ preference['getter_name'] }}().equals(component.{{ preference['getter_name']}}())){
            return true;
        }
        {% else %}if(settings.{{ preference['java_name'] }} != component.{{ preference['getter_name']}}()){
            return false;
        }{% endif %}{% endfor %}
        return false;
    }

    @Override
    public void reset() {
        RobotPreferences settings = RobotPreferences.getInstance();
        {% for preference in preferences %}
        component.{{ preference['setter_name']}}(settings.{{ preference['getter_name'] }}());{% endfor %}
    }

    @Override
    public void apply() throws ConfigurationException {
        RobotPreferences settings = RobotPreferences.getInstance();
        String s;
        {% for preference in preferences %}
        s = settings.{{ preference['validate_name'] }}(component.{{ preference['getter_name']}}());
        if(!s.isEmpty()) {
            throw new ConfigurationException("Error in {{ preference['visible_name'] }}:\\n" + s);
        }{% endfor %}
        {% for preference in preferences %}
        settings.{{ preference['setter_name'] }}(component.{{ preference['getter_name']}}());{% endfor %}
    }
}
'''

TEMPLATE_ROBOT_PREFERENCES = '''package robocorp.robot.intellij;

import com.google.gson.*;
import com.intellij.openapi.components.PersistentStateComponent;
import com.intellij.openapi.components.ServiceManager;
import com.intellij.openapi.components.State;
import com.intellij.openapi.components.Storage;
import com.intellij.openapi.diagnostic.Logger;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import robocorp.lsp.intellij.LanguageServerDefinition;

import java.util.Collection;
import java.util.concurrent.CopyOnWriteArraySet;


class RobotState {
    {% for preference in preferences %}
    public String {{ preference['java_name'] }} = "";{% endfor %}
}

// IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
@State(name = "RobotPreferences", storages = {@Storage("RobotPreferences.xml")})
public class RobotPreferences implements PersistentStateComponent<RobotState> {

    {% for preference in preferences %}
    public static final String {{ preference['constant_name'] }} = "{{ preference['dotted_name'] }}";{% endfor %}
    
    private static final Logger LOG = Logger.getInstance(RobotPreferences.class);

    // IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
    @Nullable
    @Override
    public RobotState getState() {
        RobotState robotState = new RobotState();
        {% for preference in preferences %}
        robotState.{{ preference['java_name'] }} = {{ preference['getter_name'] }}();{% endfor %}
        return robotState;
    }

    // IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
    @Override
    public void loadState(@NotNull RobotState robotState) {
        {% for preference in preferences %}
        {{ preference['setter_name'] }}(robotState.{{ preference['java_name'] }});{% endfor %}
    }
    
    // IMPORTANT: Autogenerated. Don't change manually. Run codegen.py to regenerate.
    public JsonObject asJsonObject() {
        Gson g = new Gson();
        JsonObject jsonObject = new JsonObject();
        {% for preference in preferences %}
        if(!{{ preference['java_name'] }}.isEmpty()){
            try {
                jsonObject.add({{ preference['constant_name'] }}, {{ preference['json_load'] }});
            } catch(Exception e) {
                LOG.error(e);
            }
        }
        {% endfor %}
        return jsonObject;
    }

    {% for preference in preferences %}
    private String {{ preference['java_name'] }} = "";

    public String {{ preference['getter_name'] }}() {
        return {{ preference['java_name'] }};
    }
    
    public String {{ preference['validate_name'] }}(String {{ preference['java_name'] }}) {
        if({{ preference['java_name'] }}.isEmpty()) {
            return "";
        }
        try {
            Gson g = new Gson();
            {{ preference['json_load'] }};
            {% if preference.get('enum') %} {% for enum_value in preference.get('enum') %}
            if({{ preference['java_name'] }}.equals("{{ enum_value }}")){
                return "";
            }{% endfor %}
            return "Unexpected value: " + {{ preference['java_name'] }};
            {% else %}
            return "";
            {% endif %}
        } catch(Exception e) {
            return e.toString();
        }
    }

    public void {{ preference['setter_name'] }}(String s) {
        if (s == null) {
            s = "";
        }
        if (s.equals({{ preference['java_name'] }})) {
            return;
        }
        String old = {{ preference['java_name'] }};
        {{ preference['java_name'] }} = s;
        for (LanguageServerDefinition.IPreferencesListener listener : listeners) {
            listener.onChanged({{ preference['constant_name'] }}, old, s);
        }
    }
    {% endfor %}

    private Collection<LanguageServerDefinition.IPreferencesListener> listeners = new CopyOnWriteArraySet<>();

    public static RobotPreferences getInstance() {
        return ServiceManager.getService(RobotPreferences.class);
    }

    public void addListener(LanguageServerDefinition.IPreferencesListener listener) {
        listeners.add(listener);
    }
    
    public void removeListener(LanguageServerDefinition.IPreferencesListener listener) {
        listeners.remove(listener);
    }

}
'''


def main():
    import json
    from jinja2 import Template
    import textwrap

    preferences = []
    this_dir = os.path.dirname(__file__)
    with open(os.path.join(this_dir, '..', 'robotframework-ls', 'package.json')) as stream:
        package_json = json.load(stream)
        properties = package_json['contributes']['configuration']['properties']
        for prop_name, prop_value in properties.items():
            if prop_name == 'robot.editor.4spacesTab':
                continue

            description = prop_value.get('description', '').replace('"', '\\"')
            final_desc = ''
            for d in description.split('\n'):
                d = '\\n'.join(textwrap.wrap(d, 100))
                d += '\\n'
                final_desc += d
            if prop_value['type'] in ['array', 'object']:
                final_desc += 'Note: expected as JSON ' + prop_value['type'].title() + '\\n'

            final_desc += '\\n'

            prop_value['description'] = final_desc
            prop_value['dotted_name'] = prop_name
            prop_value['constant_name'] = prop_name.replace('.', '_').replace('-', '_').upper()
            visible_name = prop_name.replace('robot.', '')
            prop_value['visible_name'] = visible_name.replace('.', ' ').replace('-', ' ').replace('_', ' ').title()
            base_name = prop_name.replace('.', ' ').replace('-', ' ').replace('_', ' ').title().replace(' ', '')
            java_name = prop_value['java_name'] = base_name[0].lower() + base_name[1:]
            prop_value['getter_name'] = 'get' + base_name[0].upper() + base_name[1:]
            prop_value['setter_name'] = 'set' + base_name[0].upper() + base_name[1:]
            prop_value['validate_name'] = 'validate' + base_name[0].upper() + base_name[1:]

            if prop_value['type'] == 'array':
                json_load = f'g.fromJson({java_name}, JsonArray.class)'

            elif prop_value['type'] == 'object':
                json_load = f'g.fromJson({java_name}, JsonObject.class)'

            elif prop_value['type'] == 'string':
                json_load = f'new JsonPrimitive({java_name})'
                
            elif prop_value['type'] == 'number':
                json_load = f'new JsonPrimitive(Integer.parseInt({java_name}))'
                
            else:
                raise AssertionError('Unhandled type: ' + prop_value['type'])

            prop_value['json_load'] = json_load

            preferences.append(prop_value)

    target = os.path.join(this_dir, 'src', 'main', 'java', 'robocorp', 'robot', 'intellij', 'RobotPreferencesPage.java')
    new_contents = Template(TEMPLATE_ROBOT_PREFERENCES_PAGE).render(preferences=preferences)
    with open(target, 'w') as stream:
        stream.write(new_contents)
    print('Written: ', target)

    target = os.path.join(this_dir, 'src', 'main', 'java', 'robocorp', 'robot', 'intellij', 'RobotPreferences.java')
    new_contents = Template(TEMPLATE_ROBOT_PREFERENCES).render(preferences=preferences)
    with open(target, 'w') as stream:
        stream.write(new_contents)
    print('Written: ', target)


if __name__ == '__main__':
    main()
