# fmt: off
# Warning: Don't edit file (autogenerated from python -m dev codegen).

OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"
OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"
OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"
OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"
OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"
OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"
OPTION_TITLE = "title"
OPTION_TYPE = "type"
OPTION_PROPERTIES = "properties"

ALL_ROBOT_OPTIONS = frozenset(
    (
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
        OPTION_TITLE,
        OPTION_TYPE,
        OPTION_PROPERTIES,
    )
)

# fmt: on
