# Warning: Don't edit file (autogenerated from python -m dev codegen).

ROBOCORP_LANGUAGE_SERVER_TCP_PORT = "robocorp.language-server.tcp-port"
ROBOCORP_LANGUAGE_SERVER_ARGS = "robocorp.language-server.args"
ROBOCORP_LANGUAGE_SERVER_PYTHON = "robocorp.language-server.python"
ROBOCORP_RCC_LOCATION = "robocorp.rcc.location"
ROBOCORP_RCC_ENDPOINT = "robocorp.rcc.endpoint"
ROBOCORP_RCC_CONFIG_LOCATION = "robocorp.rcc.config_location"

ALL_ROBOCORP_OPTIONS = frozenset(
    (
        ROBOCORP_LANGUAGE_SERVER_TCP_PORT,
        ROBOCORP_LANGUAGE_SERVER_ARGS,
        ROBOCORP_LANGUAGE_SERVER_PYTHON,
        ROBOCORP_RCC_LOCATION,
        ROBOCORP_RCC_ENDPOINT,
        ROBOCORP_RCC_CONFIG_LOCATION,
    )
)
