# fmt: off
# Warning: Don't edit file (autogenerated from python -m dev codegen).

ROBOCORP_LANGUAGE_SERVER_TCP_PORT = "robocorp.language-server.tcp-port"
ROBOCORP_LANGUAGE_SERVER_ARGS = "robocorp.language-server.args"
ROBOCORP_LANGUAGE_SERVER_PYTHON = "robocorp.language-server.python"
ROBOCORP_RCC_LOCATION = "robocorp.rcc.location"
ROBOCORP_RCC_ENDPOINT = "robocorp.rcc.endpoint"
ROBOCORP_RCC_CONFIG_LOCATION = "robocorp.rcc.config_location"
ROBOCORP_HOME = "robocorp.home"
ROBOCORP_VERIFY_LSP = "robocorp.verifyLSP"
ROBOCORP_AUTO_SET_PYTHON_EXTENSION_INTERPRETER = "robocorp.autoSetPythonExtensionInterpreter"
ROBOCORP_AUTO_SET_PYTHON_EXTENSION_DISABLE_ACTIVATE_TERMINAL = "robocorp.autoSetPythonExtensionDisableActivateTerminal"
ROBOCORP_PROCEED_WITH_LONG_PATHS_DISABLED = "robocorp.proceedWithLongPathsDisabled"
ROBOCORP_VAULT_TOKEN_TIMEOUT_IN_MINUTES = "robocorp.vaultTokenTimeoutInMinutes"
ROBOCORP_CODE_LENS_ROBO_LAUNCH = "robocorp.codeLens.roboLaunch"
ROBOCORP_ACTION_SERVER_LOCATION = "robocorp.actionServer.location"

ALL_ROBOCORP_OPTIONS = frozenset(
    (
        ROBOCORP_LANGUAGE_SERVER_TCP_PORT,
        ROBOCORP_LANGUAGE_SERVER_ARGS,
        ROBOCORP_LANGUAGE_SERVER_PYTHON,
        ROBOCORP_RCC_LOCATION,
        ROBOCORP_RCC_ENDPOINT,
        ROBOCORP_RCC_CONFIG_LOCATION,
        ROBOCORP_HOME,
        ROBOCORP_VERIFY_LSP,
        ROBOCORP_AUTO_SET_PYTHON_EXTENSION_INTERPRETER,
        ROBOCORP_AUTO_SET_PYTHON_EXTENSION_DISABLE_ACTIVATE_TERMINAL,
        ROBOCORP_PROCEED_WITH_LONG_PATHS_DISABLED,
        ROBOCORP_VAULT_TOKEN_TIMEOUT_IN_MINUTES,
        ROBOCORP_CODE_LENS_ROBO_LAUNCH,
        ROBOCORP_ACTION_SERVER_LOCATION,
    )
)

# fmt: on
