# Warning: Don't edit file (autogenerated from python -m dev codegen).

ROBOCODE_GET_LANGUAGE_SERVER_PYTHON = "robocode.getLanguageServerPython"  # Get a python executable suitable to start the language server.
ROBOCODE_CREATE_ACTIVITY = "robocode.createActivity"  # Create a Robocode Activity Package.
ROBOCODE_LIST_ACTIVITY_TEMPLATES_INTERNAL = "robocode.listActivityTemplates.internal"  # Provides a list with the available activity templates.
ROBOCODE_CREATE_ACTIVITY_INTERNAL = "robocode.createActivity.internal"  # Actually calls rcc to create the activity.

ALL_SERVER_COMMANDS = [
    ROBOCODE_LIST_ACTIVITY_TEMPLATES_INTERNAL,
    ROBOCODE_CREATE_ACTIVITY_INTERNAL,
]
