channels:
    - conda-forge

dependencies:
    - python=3.9.13

    # https://pip.pypa.io/en/stable/news/
    - pip=22.1.2
    - pywin32=303

    - pip:
          - robocorp-inspector==0.8.1
          - robotframework==4.1
