channels:
    - conda-forge

dependencies:
    - python=3.9.13

    # https://pip.pypa.io/en/stable/news/
    - pip=22.1.2

    # https://anaconda.org/conda-forge/python.app/files
    - python.app=1.3

    - pip:
          - robocorp-inspector==0.8.1
          - robotframework==4.1
