# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.9.13 # https://pyreadiness.org/3.9/
    - pip=22.1.2 # https://pip.pypa.io/en/stable/news/
    - pywin32=303 # https://github.com/mhammond/pywin32/blob/main/CHANGES.txt
    - pyyaml=6.0
    - pip:
          - robocorp-inspector==0.9.1 # https://github.com/robocorp/inspector/blob/master/CHANGELOG.md
          - robotframework==5.0.1 # https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.1.rst
