channels:
    - conda-forge

dependencies:
    - python=3.9.13

    # https://pip.pypa.io/en/stable/news/
    - pip=22.1.2

    # https://anaconda.org/conda-forge/pyqt/files
    - pyqt=5.12.3

    - pip:
          - robocorp-inspector==0.8.2
          - robotframework==4.1
