#!/usr/bin/env bash
set -eux

pushd src
  python -m pip install -e . --ignore-installed --no-deps
popd

jupyter labextension install --no-build \
  @jupyter-widgets/jupyterlab-manager@1.1.0 \
  @krassowski/jupyterlab-lsp@0.7.1 \
  jupyterlab_robotmode@1.1.1

jupyter lab build --dev-build=False --minimize=True
